import mirrorCreator from 'mirror-creator';

export default mirrorCreator([
  'SIGNING_IN_USER',
  'SIGN_IN_SUCCESSFUL',
  'SIGN_IN_ERROR',
  'UPDATE_NAME',
  'UPDATE_HIGH_RISK',
  'UPDATE_MILITARY_SERVICE_YEARS',
  'UPDATE_MILITARY_SERVICE_MONTHS',
  'UPDATE_MILITARY_SERVICE_DAYS',
  'UPDATE_ESTIMATED_RETIREMENT_SALARY',
  'UPDATE_ESTIMATED_RETIREMENT_HIGH',
  'UPDATE_SSB',
  'UPDATE_MONTHLY_TSP_DISBURSEMENT',
  'UPDATE_ANNUAL_UNUSED_LEAVE',
  'UPDATE_ANNUAL_SICK_UNUSED_LEAVE',
  'UPDATE_SURVIVOR_BENEFIT_DEDUCTION',
  'UPDATE_SURVIVOR_BENEFIT_OPTION'
]);
