import mirrorCreator from 'mirror-creator';

export default mirrorCreator([
  'SIGNING_IN_USER',
  'SIGN_IN_SUCCESSFUL',
  'SIGN_IN_ERROR',
  'UPDATE_NAME',
  'UPDATE_HIGH_RISK',
  'MILITARY_SERVICE_YEARS',
  'MILITARY_SERVICE_MONTHS',
  'MILITARY_SERVICE_DAYS',
  'ESTIMATED_RETIREMENT_SALARY',
  'ESTIMATED_RETIREMENT_HIGH'
]);
